package musicsocial;

import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JFrame;

import java.util.*;
import java.lang.StringBuffer; //For concating strings


//Input validation stuff


public class newReg extends javax.swing.JFrame {

    
    //array list help https://beginnersbook.com/2013/12/java-arraylist/
    public static ArrayList<String> myFaveList = new ArrayList<String>(); //List to store elements for the favourites
    
    public void databaseaddition(String username, String dob, String pob, String favgenre) {
        try {

            Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/MusicSocialdb", "MSDB", "MSDB1");
            Statement statment = conn.createStatement();

            int execute;
            execute = statment.executeUpdate("INSERT INTO MSDB.usertable VALUES ('" + username + "','" + pob + "','" + dob + "','" + favgenre + "')");
            JOptionPane.showMessageDialog(null, "Registration Successful. Please Go back to the Login Page");
        } catch (SQLException e) {

            if (e.getErrorCode() == -20001) {
                JOptionPane.showMessageDialog(null, "Registration Unsuccessful. Please use a different username.");
            }
            System.out.println(e.getErrorCode());

        }

    }
    //Creates new form newReg
    public void fave_text_add(String input){ //Adds text to the global array and favourite genre box
        
        if (!myFaveList.contains(input)){ //If doesn't contain then continue
         myFaveList.add(input); //add the input to the list
         //list_fave.add(0 , input);
        }
       
    
    }
    public void fave_text_remove(String input){ //Removess text from the global array and favourite genre box
        
        if (myFaveList.contains(input)){ //if contains then continune
         myFaveList.remove(input); //remove input from the list   
        }
     
    
    }
    public void update_fave_text(){
        StringBuffer temp = new StringBuffer(); //Used to add each string from the list and the next line
        String result; //Final string
        
        for (int i = 0; i < myFaveList.size();i++){//loop start
        temp.append(myFaveList.get(i));
        temp.append("\n"); //New line
                    
        } //loop end
        
        result = temp.toString(); //Move string buffer to normal string data type
        
        txt_fave_area.setText(result);
    }
    
   public void validate_inputs(){
       
       try{//try start
           
       }//try end
       catch(Exception e){ //ex start
           
       } //ex end
   }

    public newReg() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_PlaceOfBirth = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        registerbutton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        loginbutton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        fave_text_combobox = new javax.swing.JComboBox<>();
        btn_fav_add = new javax.swing.JButton();
        btn_fav_remove = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_fave_area = new javax.swing.JTextArea();
        DoB_D = new javax.swing.JTextField();
        DoB_Y = new javax.swing.JTextField();
        DoB_M = new javax.swing.JTextField();
        DoB_slash1 = new javax.swing.JLabel();
        DoB_slash2 = new javax.swing.JLabel();
        Lb_Title = new javax.swing.JLabel();
        btn_fav_bot = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Username");
        jLabel1.setToolTipText("");

        jLabel2.setText("Place of Birth");

        jLabel3.setText("Date of Birth");

        registerbutton1.setText("Register");
        registerbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbutton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Favourite Genres");

        loginbutton.setText("Login");
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });

        fave_text_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rock", "Pop", "Techno", "Opera", "Drum and Bass", "Hip Hop", "Dubstep", "Reggae", "UK Garage", "Grime" }));
        fave_text_combobox.setToolTipText("Select in the Drop-box and edit with the buttons");
        fave_text_combobox.setMinimumSize(new java.awt.Dimension(100, 20));
        fave_text_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fave_text_comboboxActionPerformed(evt);
            }
        });

        btn_fav_add.setText("ADD");
        btn_fav_add.setMinimumSize(new java.awt.Dimension(75, 35));
        btn_fav_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fav_addActionPerformed(evt);
            }
        });

        btn_fav_remove.setText("REMOVE SPECIFIC");
        btn_fav_remove.setMinimumSize(new java.awt.Dimension(75, 35));
        btn_fav_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fav_removeActionPerformed(evt);
            }
        });

        txt_fave_area.setEditable(false);
        txt_fave_area.setColumns(20);
        txt_fave_area.setRows(5);
        txt_fave_area.setPreferredSize(new java.awt.Dimension(150, 90));
        jScrollPane1.setViewportView(txt_fave_area);

        DoB_D.setText("DD");
        DoB_D.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DoB_DFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DoB_DFocusLost(evt);
            }
        });
        DoB_D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoB_DActionPerformed(evt);
            }
        });

        DoB_Y.setText("YYYY");
        DoB_Y.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DoB_YFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DoB_YFocusLost(evt);
            }
        });
        DoB_Y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoB_YActionPerformed(evt);
            }
        });

        DoB_M.setText("MM");
        DoB_M.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DoB_MFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DoB_MFocusLost(evt);
            }
        });
        DoB_M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoB_MActionPerformed(evt);
            }
        });

        DoB_slash1.setText("/");

        DoB_slash2.setText("/");

        Lb_Title.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lb_Title.setText("REGISTRATION");

        btn_fav_bot.setText("REMOVE RECENT");
        btn_fav_bot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fav_botActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(registerbutton1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(loginbutton)
                                .addGap(25, 25, 25))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fave_text_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_fav_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_fav_remove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_fav_bot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(129, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_PlaceOfBirth)
                                    .addComponent(txt_username)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(DoB_D, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(DoB_slash1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(DoB_M, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)
                                        .addComponent(DoB_slash2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(DoB_Y, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lb_Title))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lb_Title)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_PlaceOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DoB_slash1)
                        .addComponent(DoB_M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DoB_Y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DoB_slash2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(DoB_D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fave_text_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_fav_add, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_fav_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_fav_bot, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerbutton1)
                    .addComponent(loginbutton))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbutton1ActionPerformed
        //databaseaddition(username.getText(), dob.getText(), pob.getText(), favgenre.getText());
    }//GEN-LAST:event_registerbutton1ActionPerformed

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
        JFrame frame = new Login();
        frame.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_loginbuttonActionPerformed

    private void btn_fav_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fav_removeActionPerformed
    String temp = fave_text_combobox.getSelectedItem().toString();
    fave_text_remove(temp);
    update_fave_text();
    }//GEN-LAST:event_btn_fav_removeActionPerformed

    private void btn_fav_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fav_addActionPerformed
        // TODO add your handling code here:
        
    String temp = fave_text_combobox.getSelectedItem().toString();
    fave_text_add(temp);
    update_fave_text();
    }//GEN-LAST:event_btn_fav_addActionPerformed

    private void fave_text_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fave_text_comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fave_text_comboboxActionPerformed

    private void DoB_DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoB_DActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoB_DActionPerformed

    private void DoB_YActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoB_YActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoB_YActionPerformed

    private void DoB_MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoB_MActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoB_MActionPerformed

    private void DoB_DFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DoB_DFocusGained
        // TODO add your handling code here:
        if (DoB_D.getText().equals("DD")) //When the user clicks on, clear the box
        {
            DoB_D.setText("");
        }
    }//GEN-LAST:event_DoB_DFocusGained

    private void DoB_DFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DoB_DFocusLost
        // TODO add your handling code here:
        if (DoB_D.getText().equals("")) //When the user clicks on, clear the box
        {
            DoB_D.setText("DD");
        }
    }//GEN-LAST:event_DoB_DFocusLost

    private void DoB_MFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DoB_MFocusGained
        // TODO add your handling code here:
        if (DoB_M.getText().equals("MM")) //When the user clicks on, clear the box
        {
            DoB_D.setText("");
        }
    }//GEN-LAST:event_DoB_MFocusGained

    private void DoB_MFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DoB_MFocusLost
        // TODO add your handling code here:
        if (DoB_M.getText().equals("")) //When the user clicks on, clear the box
        {
            DoB_D.setText("MM");
        }
    }//GEN-LAST:event_DoB_MFocusLost

    private void DoB_YFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DoB_YFocusGained
        // TODO add your handling code here:
        if (DoB_Y.getText().equals("YYYY")) //When the user clicks on, clear the box
        {
            DoB_D.setText("");
        }
    }//GEN-LAST:event_DoB_YFocusGained

    private void DoB_YFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DoB_YFocusLost
        // TODO add your handling code here:
        if (DoB_Y.getText().equals("")) //When the user clicks on, clear the box
        {
            DoB_D.setText("YY");
        }
    }//GEN-LAST:event_DoB_YFocusLost

    private void btn_fav_botActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fav_botActionPerformed
        // TODO add your handling code here:
    String temp = myFaveList.remove(myFaveList.size() - 1);
    fave_text_remove(temp);
    update_fave_text();
    }//GEN-LAST:event_btn_fav_botActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
                
//                //Number format stuff so the user can only input numbers at certain points
//                NumberFormat intFormat = NumberFormat.getIntegerInstance();
//                NumberFormatter intFormatter = new NumberFormatter(intFormat);
//                intFormatter.setValueClass(int.class);
//                intFormatter.setAllowsInvalid(false); //Doesn't allow invalid inputs
//                intFormatter.setMinimum(1); //Set the minimum input
//                
//                JFormattedTextField myField = new JFormattedTextField(intFormatter);
//                JOptionPane.showMessageDialog(null, myField);
//                
//                System.out.println(myField.getValue());
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newReg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DoB_D;
    private javax.swing.JTextField DoB_M;
    private javax.swing.JTextField DoB_Y;
    private javax.swing.JLabel DoB_slash1;
    private javax.swing.JLabel DoB_slash2;
    private javax.swing.JLabel Lb_Title;
    private javax.swing.JButton btn_fav_add;
    private javax.swing.JButton btn_fav_bot;
    private javax.swing.JButton btn_fav_remove;
    private javax.swing.JComboBox<String> fave_text_combobox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton loginbutton;
    private javax.swing.JButton registerbutton1;
    public javax.swing.JTextField txt_PlaceOfBirth;
    private javax.swing.JTextArea txt_fave_area;
    public javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables

}
