package musicsocial;

import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JFrame;

import java.util.*;
import java.lang.StringBuffer; 

public class newReg extends javax.swing.JFrame {

    
    //array list help https://beginnersbook.com/2013/12/java-arraylist/
    public static ArrayList<String> myFaveList = new ArrayList<String>(); //List to store elements for the favourites
    
    
    public void databaseaddition(String username, String dob, String pob, String favgenre) {
        try {

            Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/MusicSocialdb", "MSDB", "MSDB1");
            Statement statment = conn.createStatement();

            int execute;
            execute = statment.executeUpdate("INSERT INTO MSDB.usertable VALUES ('" + username + "','" + pob + "','" + dob + "','" + favgenre + "')");
            JOptionPane.showMessageDialog(null, "Registration Successful. Please Go back to the Login Page");
        } catch (SQLException e) {

            if (e.getErrorCode() == -20001) {
                JOptionPane.showMessageDialog(null, "Registration Unsuccessful. Please use a different username.");
            }
            System.out.println(e.getErrorCode());

        }

    }
    //Creates new form newReg
    public void fave_text_add(String input){ //Adds text to the global array and favourite genre box
        
        if (!myFaveList.contains(input)){ //If doesn't contain then continue
         myFaveList.add(input); //add the input to the list    
        }
       
    
    }
    public void fave_text_remove(String input){ //Removess text from the global array and favourite genre box
        
        if (myFaveList.contains(input)){ //if contains then continune
         myFaveList.remove(input); //remove input from the list   
        }
     
    
    }
    public void update_fave_text(){
        StringBuffer temp = new StringBuffer(); //Used to add each string from the list and the next line
        String result = new String();
        
        for (int i = 0; i < myFaveList.size();i++){//loop start
        temp.append(myFaveList.get(i));
        temp.append("\n"); //New line
                    
        } //loop end
        
        result = temp.toString(); //Move string buffer to normal string data type
        
        txt_fave_area.setText(result);
    }
    
    
    public newReg() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pob = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dob = new javax.swing.JTextField();
        registerbutton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        favgenre = new javax.swing.JTextField();
        loginbutton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        fave_text_combobox = new javax.swing.JComboBox<>();
        btn_fav_add = new javax.swing.JButton();
        btn_fav_remove = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_fave_area = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Username");
        jLabel1.setToolTipText("");

        jLabel2.setText("Place of Birth");

        jLabel3.setText("Date of Birth");

        registerbutton1.setText("Register");
        registerbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbutton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Favourite Genres");

        loginbutton.setText("Login");
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });

        fave_text_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rock", "Pop", "Techno", "Opera", "Drum and Bass", "Hip Hop", "Dubstep", "Reggae", "UK Garage", "Grime" }));
        fave_text_combobox.setToolTipText("Select in the Drop-box and edit with the buttons");
        fave_text_combobox.setMinimumSize(new java.awt.Dimension(100, 20));
        fave_text_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fave_text_comboboxActionPerformed(evt);
            }
        });

        btn_fav_add.setText("ADD");
        btn_fav_add.setMinimumSize(new java.awt.Dimension(75, 35));
        btn_fav_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fav_addActionPerformed(evt);
            }
        });

        btn_fav_remove.setText("REMOVE");
        btn_fav_remove.setMinimumSize(new java.awt.Dimension(75, 35));
        btn_fav_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fav_removeActionPerformed(evt);
            }
        });

        txt_fave_area.setColumns(20);
        txt_fave_area.setRows(5);
        txt_fave_area.setPreferredSize(new java.awt.Dimension(150, 90));
        jScrollPane1.setViewportView(txt_fave_area);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(registerbutton1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(loginbutton)
                                .addGap(25, 25, 25))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fave_text_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_fav_remove, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(btn_fav_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(dob, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(pob, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(username, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(favgenre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(favgenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fave_text_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_fav_add, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btn_fav_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 43, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerbutton1)
                    .addComponent(loginbutton))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbutton1ActionPerformed
        databaseaddition(username.getText(), dob.getText(), pob.getText(), favgenre.getText());
    }//GEN-LAST:event_registerbutton1ActionPerformed

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
        JFrame frame = new Login();
        frame.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_loginbuttonActionPerformed

    private void btn_fav_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fav_removeActionPerformed
    String temp = fave_text_combobox.getSelectedItem().toString();
    fave_text_remove(temp);
    update_fave_text();
    }//GEN-LAST:event_btn_fav_removeActionPerformed

    private void btn_fav_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fav_addActionPerformed
        // TODO add your handling code here:
        
    String temp = fave_text_combobox.getSelectedItem().toString();
    fave_text_add(temp);
    update_fave_text();
    }//GEN-LAST:event_btn_fav_addActionPerformed

    private void fave_text_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fave_text_comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fave_text_comboboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newReg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_fav_add;
    private javax.swing.JButton btn_fav_remove;
    public javax.swing.JTextField dob;
    private javax.swing.JComboBox<String> fave_text_combobox;
    private javax.swing.JTextField favgenre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton loginbutton;
    public javax.swing.JTextField pob;
    private javax.swing.JButton registerbutton1;
    private javax.swing.JTextArea txt_fave_area;
    public javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

}
